config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  devise_for :usuarios
  devise_for :administradores
  
  resources :categorias
  resources :productos

  resources :carros, only: [:show, :update] do
    member do 
      post  :pagar_con_paypal
      get   :procesar_pago_paypal
    end
  end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @productos = Producto.all
    end

    
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="container">
            <div class="row">
                <% @productos.each do |producto| %> <!--Con esto trae todos los productos a la vista-->
                    <div class="col-md-3 mb-3"> <!--Cn esto se crea las tarjetas-->
                        <div class="card">
                            <img class="card-img-top" src="https://dummyimage.com/600x400/c7c7c7/737373&text=image" alt="<%=producto.nombre%>" />
                            <div class="card-block">
                                <h5 class="card-title">
                                    <%= producto.nombre %>
                                </h5>
                                <div class="card-text">
                                    <div class="badge badge-primary text-black">
                                        <%= producto.categorias.first.nombre %>
                                    </div>
                                    <div>$<%= producto.precio %>
                                    </div>
                                </div>
                                <div class="row float-right">
                                    <div class="col-md-12">
                                        <%= form_for :carro, url: carro_path(0), method: :put do |f| %>
                                            <%= f.hidden_field :producto_id, value: producto.id %>
                                            <%= f.hidden_field :cantidad, value: 1 %>
                                            <%= f.submit 'Agregar al carrito', class: 'btn btn-primary btn-sm' %>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>